image:
  file: .gitpod.dockerfile
#tasks:
#- init: docker-compose up -d
#  command: java -jar target/*.jar
#
# exposed ports
#ports:
#- port: 8080
#  onOpen: open-preview
#
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
