#image:
#  file: .gitpod.dockerfile
tasks:
- init: docker-compose -f controleOperacional/src/main/docker/mysql.yml up -d
- command:  nvm install v16.14.2 && sleep 5
- command:  nvm use v16.14.2 && sleep 5
- command:  npm install -g npm@8.6.0  && sleep 5
- command:  npm install -g generator-jhipster

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
