#image:
#  file: .gitpod.dockerfile
tasks:
- command: cd controleOperacional/ && ./mvnw  package jib:dockerBuild
- init: docker ps #-compose -f controleOperacional/src/main/docker/mysql.yml up -d
- command: nvm install v16.14.2 && sleep 1 && nvm use v16.14.2 && sleep 1 && npm -v && npm install -g npm@8.6.0 && npm -v && sleep 1 && npm install -g generator-jhipster

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
