#image:
#  file: .gitpod.dockerfile
tasks:
- init: nvm install v16.14.2 && nvm use v16.14.2 && npm -v && npm install -g npm@8.6.0 && npm -v && npm install -g generator-jhipster
- command: docker images #-compose -f controleOperacional/src/main/docker/mysql.yml up -d
- command: cd controleOperacional/ && ./mvnw  package jib:dockerBuild && docker images

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
