#image:
#  file: .gitpod.dockerfile
tasks:
#- init: docker-compose -f controleOperacional/src/main/docker/mysql.yml up -d
- command:  nvm install v16.14.2 && sleep 2 && nvm use v16.14.2 && sleep 2 && npm -v && npm install -g npm@8.6.0 && npm -v && sleep 2 && npm install -g generator-jhipster

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
