# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MzNlOGExNDE2MTI1ZWEyMTQ4YzI3NjNlYTNiMmZmM2I1N2U5OTI1N2MwM2ZlM2VjZGFkZDMzYjM2NjNjYTdmYzU4M2YwNDQ3ZTQ0MDIzZDcwMjUwM2E1YTQ1ZDFmZDZmYzZmZWE3NTcwZWY3YjJhMjVlMDIyYzVkZDE3YTIwMWM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
