# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZmQ5Mzk4NjAyMTEyMjIwMzNkYmEzOTk0MDRiNzlhNjA4OGFlNmRjMmFlMWJlMzdjZGI3OGVjOWRlZjViM2RiNzA4ODM3OTYxNzcxNGU1OTkyMTJhODNiYjUxZjc5MDAzMTk5ZGQzZDk2ZTdhZjQ0NjZlOWNmNDNhYjg1MDczZGQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
