# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: M2U1NGI4ODJiNjc3NDBmNTI2YWI1MDQ5YTRmOGNhZjdjM2QzZmM5NWY0ODY1NTVjMWMyMWMzZjYzZmY3NDJmM2ZjYjJhMmQyMGExM2NiMjEyYWZlMzFkYjFmM2RlOGVjYTIzZDI3YmM3NTg2NmIwNGFhZmI0YzhiMDBkYjM5YjE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
