# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzFjN2RkMTRjNTc4ZmM5MDczOTBiMWQyNzU1ZDY4MDRiNTNkYjgxYTVhZTE1NGQ2ZTE4YTdjY2Y4NTdlMWJiNzZmODgwMDdlYTgxOGQyYjI0OGIyOTIyN2FhOGQxYmVkOTdlZDk3MmIyODI2YmY2OGQyZjAwNDNhOTNhZjEzOWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
